### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by satyajitghana** [hay-001/MODNet-Multi-offset-Point-Cloud-Denoising-Network#1]
Where can i find the link to pretrained model to test on my dataset?

**Comment by hay-001** [comment]
Due to the recent code optimization, the original pre-training model cannot be used temporarily. We will upload it later. If you need to use it urgently, it is suggested that you can train directly. The training is very stable and can easily reproduce the results of the paper. And the training time is very short, about 4-6 h. Sorry for the inconvenience.

**Comment by hay-001** [comment]
You can download the Pre-trained model now.
